### ISSUE TITLE
'StandaloneHTMLBuilder' has no attribute 'default_sidebars'

### ISSUE THREAD

**Issue by mrichar1** [Robpol86/sphinxcontrib-versioning#41]
Getting this error with `sphinx` `1.6.3` - a quick look at this class does indeed show that it doesn't have this attribute any more - but previous versions did.

```
# Sphinx version: 1.6.3
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/tmp/venv/lib/python3.5/site-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/tmp/venv/lib/python3.5/site-packages/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/tmp/venv/lib/python3.5/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/tmp/venv/lib/python3.5/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/tmp/venv/lib/python3.5/site-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
```

**Comment by mrichar1** [comment]
Just realised this is a dup of #39
