### ISSUE TITLE
Failed to get dates for all remote commits

### ISSUE THREAD

**Issue by senaps** [Robpol86/sphinxcontrib-versioning#42]
this is the error that i get while trying to build the versions! :)
"Failed to get dates for all remote commits"

=> Reading config from source/conf.py...
Running Sphinx v1.6.3
loading pickled environment... not yet created

Exception occurred:
  File "/home/senaps/Projects/documents/testversion/env/lib/python2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
The full traceback has been saved in /tmp/sphinx-err-0FisJh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/senaps/Projects/documents/testversion/env/lib/python2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 219, in _read_config
    _build(argv, config, Versions(list()), current_name, False)
  File "/home/senaps/Projects/documents/testversion/env/lib/python2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
SphinxError
=> sphinx-build failed for branch/tag while reading config: <local>
=> Unable to read file, continuing with only CLI args.
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
Username for 'http://<ip>': maysam
Password for 'http://maysam@<ip>': 
=> Found: feature master 1.0.0
=> Failed to get dates for all remote commits.

**Comment by jgomo3** [comment]
I Have the same problem. This is the log:

```
# Sphinx version: 1.6.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/monkey/.local/share/virtualenvs/docs-NpS6InWB/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/monkey/.local/share/virtualenvs/docs-NpS6InWB/lib/python3.5/site-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/home/monkey/.local/share/virtualenvs/docs-NpS6InWB/lib/python3.5/site-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/home/monkey/.local/share/virtualenvs/docs-NpS6InWB/lib/python3.5/site-packages/sphinx/application.py", line 488, in emit
    return self.events.emit(event, self, *args)
  File "/home/monkey/.local/share/virtualenvs/docs-NpS6InWB/lib/python3.5/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/monkey/.local/share/virtualenvs/docs-NpS6InWB/lib/python3.5/site-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'

```

**Comment by FraBle** [comment]
+1

**Comment by ncmaas** [comment]
I resolved this issue for now by downgrading my sphinx to 1.5.6 from 1.6.3.

**Comment by priyasha1** [comment]
**I am facing the similar issue...**

_[36m=> Gathering info about the remote git repository...[39m
[36m=> Getting list of all remote branches/tags...[39m
[36m=> Found: add_OrderedDictField any_value_fixes array_fix async_requests attribute_map auto_load_model_fix custom_serializers datetime-field decimal_expansion deep_copy_fix demandware demandware_test dict_model dictionary_optimization dranger/core-improvements drop_py26_testing earlier_model_property_check error_fix example_data feature/BOO-930 feature/PLAT-146-move-test-decorators-to-core feature/correct-pip-module-name field_descriptions fix_translator_check_field length_validator list_validator_error_message_fix make_a_pip_module master model-dev model-dev-PR model_documentation_generator model_help model_nested_types new_sphinx_versioning optimization ordered-dict-attrib-map ordereddict_fix pickling_support repr requirements_update restrict_auto_load revert sphinx_docs sphinx_versioning stevens-branch strip strip-to-model translator_fix translator_input_casting translators try_convert value_feild_fix[39m
[31m=> Failed to get dates for all remote commits.[39m
Failure.
Build step 'Execute shell' marked build as failure
Finished: FAILURE_




**is thr any solution other than downgrading sphinx? please help!**

**Comment by pstorz** [comment]
I could solve this problem by updating git to a 2.x version (was 1.8 before)

**Comment by keyjhk** [comment]
> I could solve this problem by updating git to a 2.x version (was 1.8 before)

it really works.thank you.
