### ISSUE TITLE
how to use in the right way?

### ISSUE THREAD

**Issue by mgiaco** [Robpol86/sphinxcontrib-versioning#43]
Hi,

I do have a test project with a "doc" folder. In the doc folder I do have  a sphinx build  under "doc\build\html".

Then I run:

```python
sphinx-versioning build -r master doc doc/build/html
```
And I get:

```
=> Gathering info about the remote git repository...
=> Getting list of all remote branches/tags...
=> Found: master v1.0 v1.1 v1.2
=> With docs:
=> No docs found in any remote branch/tag. Nothing to do.
Failure.
```
So what´s wrong here i read the help but did not find the error.

many thanks

**Comment by Robpol86** [comment]
You need to commit the doc folder and push it to origin.

**Comment by mgiaco** [comment]
Okay but I already did that. Should I also commit the build in that doc folder?

**Comment by mgiaco** [comment]
Okay now I have some error:

```shell
# Sphinx version: 1.6.3
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "C:\test\lib\site-packages\sphinx\cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "C:\test\lib\site-packages\sphinx\application.py", line 234, in __init__
    self._init_builder()
  File "C:\test\lib\site-packages\sphinx\application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "C:\test\lib\site-packages\sphinx\application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "C:\test\lib\site-packages\sphinx\events.py", line 79, in emit
    results.append(callback(*args))
  File "C:\test\lib\site-packages\sphinxcontrib\versioning\sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
```

So I use the alabaster theme but I have read that it is supported.

**Comment by mgiaco** [comment]
@Levi-Armstrong no sorry. I do not search for a solution.

**Comment by twiecki** [comment]
Getting the same error.

**Comment by suush** [comment]
This error is due to newer sphinx version(1.6). #46

**Comment by gryphon2411** [comment]
Is it going to be fixed?
